# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a8cc0ef8d9a7eaa3f92fc8a99a01e6789aeea3e5d78807baee17b9e0974d315d66b1f68f4eff9d46354c0cba2451aa92940c1b5815c45d03db5a9d3f54d0048

test:
  secret_key_base: dabe892b742c1c39a5727dc77b9e79df4d0b002ee6f7dfdffac5747879fd1daaf3f9ebb0b266aa7a55b38faaa4191f2523c9a8d9dae27906fbda83470b2e593f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
